### ISSUE TITLE
upload the actual source code please

### ISSUE THREAD

**Issue by KlavierGayming** [GrowtopiaFli/beach-brother-mod-source#1]
me want

**Comment by GrowtopiaFli** [comment]
Look
beach brother was made before the fucking source code declaration klav
so this was an unfinished wip before the creator got cancelled
i dont have the old source
you make absolutely no sense
and at this time i was fking around with webms till i shared it

**Comment by KlavierGayming** [comment]
k sheesh, i didn't know. no need to get mad
